# Spring Boot Application YAML

I had a Spring Boot application. I started it with Gradle and then... surprise! An error, but no info about its reason.
```java
16:45:06: Executing task 'run'â€¦

> Task :utils:compileJava UP-TO-DATE
> Task :utils:compileGroovy NO-SOURCE
> Task :utils:processResources NO-SOURCE
> Task :utils:classes UP-TO-DATE
> Task :utils:jar UP-TO-DATE
> Task :prototypes:compileJava UP-TO-DATE
> Task :prototypes:compileGroovy NO-SOURCE
> Task :prototypes:processResources UP-TO-DATE
> Task :prototypes:classes UP-TO-DATE
> Task :prototypes:jar UP-TO-DATE
> Task :backendnew:compileJava UP-TO-DATE
> Task :backendnew:compileGroovy NO-SOURCE
> Task :backendnew:processResources UP-TO-DATE
> Task :backendnew:dependenciesFile
> Task :backendnew:generateManifest
> Task :backendnew:classes UP-TO-DATE
Connected to the target VM, address: '127.0.0.1:54568', transport: 'socket'

> Task :backend:run
16:45:14.709 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5b057c8c: startup date [Mon Jul 09 16:45:14 CEST 2018]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/user/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.0.5.RELEASE/1bd9feb1d9dac6accd27f5244b6c47cfcb55045c/spring-core-5.0.5.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:45:15.064 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
16:45:15.116 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$a135a987] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
16:45:15.338 [main] INFO  p.a.t.c.a.s.c.e.EnvironmentBootstrap - Loading implementation metadata for backend
16:45:15.355 [main] INFO  p.a.t.c.a.s.c.l.LogstashConfiguration - Statically configuring Logstash appender
Disconnected from the target VM, address: '127.0.0.1:54568', transport: 'socket'

> Task :backend:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend:run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
10 actionable tasks: 3 executed, 7 up-to-date
Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
16:45:17: Task execution finished 'run'.
```

To figure out what was going on I went with breakpoints on all uncaught exceptions
![Breakpoints on uncaught exceptions](https://raw.githubusercontent.com/mat3e/mat3e.github.io/master/blog/img/breakpoints_exceptions.png)

and started an app in a debug mode.

When paused in `ReflectionUtils`, `rethrowRuntimeException` method, line 322, I was able to take a look at the error message:
```java
Failed to load property source from location 'classpath:/application-local.yml'
while scanning a simple key
 in 'reader', line 17, column 3:
      h2:g
      ^
could not find expected ':'
 in 'reader', line 18, column 12:
        console:
               ^
```

![Exception in yaml](https://raw.githubusercontent.com/mat3e/mat3e.github.io/master/blog/img/yaml_exception.png)

Quick verification and I figured out that I literally had `h2:g` instead of `h2:` inside my _application.yml_ file:
```yaml
h2:g
  console:
    enabled: true
```

I also know that such a problem may apprear in _application.yml_, e.g. when two lines (at the same level) have a different number of whitespace characters.

I don't know why such a meaningful error message was not visible anywhere in the console, when running from Gradle. However, I'm pretty sure it will be fixed soon.
